/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package psi.parser

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class ParserTest {
    @Test
    fun `should return Provider type for my var`() {
        val parser = Parser()
        assertEquals(parser.findTypeOfMyVar(), "Provider")
    }
}
